### ISSUE TITLE
add link to the repo to start of file?

### ISSUE THREAD

**Issue by tfcarlin** [duckduckgo/content-scope-scripts#402]
Hi,

While inspecting a local web app I noticed this script. Needless to say I didn't have a clue as to why it was appear "in" my simple app.  It would have saved me a lot of effort if the file included a link to this repo.

Thanks,

Tim

**Comment by jonathanKingston** [comment]
Hey!

We've recently started doing this for another feature. I think this is a very good suggestion.

I'll add this to our next build so that people can find where to raise issues like this 👍🏻

**Comment by jonathanKingston** [comment]
Closing this out, it will be in the next release of the code :)
