### ISSUE TITLE
Add `//# sourceURL` comment to injected script

### ISSUE THREAD

**Issue by mattheww-skyward** [duckduckgo/content-scope-scripts#463]
Firefox's debugger uses URLs to preserve breakpoints between page loads.  Without a persistent URL, it's almost impossible to debug, and it makes the function of the injected script clearer as well.

Thank you!

**Comment by jonathanKingston** [comment]
Cheers for the report.
I had a toy around with this but there's some issues currently in #472; I don't think we want to hardcode the extension URL in here.
Given the two contexts for Firefox though I can see the value.
