### ISSUE TITLE
Consider using `chrome.privacy.*` APIs rather than deleting prototype members.

### ISSUE THREAD

**Issue by mikewest** [duckduckgo/content-scope-scripts#69]
Hey folks, I think y'all can get away with fewer permissions on this extension if you use `chrome.privacy.websites.privacySandboxEnabled` rather than injecting into pages to delete things from various prototypes (see https://developer.chrome.com/docs/extensions/reference/privacy/#:~:text=privacySandboxEnabled). That's also somewhat future-proof, as it should be tied to new APIs added over time as well. If there's a reason that doesn't work for you, file a bug? Likewise, other bits and pieces of that API are likely also interesting for y'all. We aim to make this kind of thing possible without the risks of host permission and content script injection. :)

**Comment by jonathanKingston** [comment]
Hey @mikewest!

So we might be able to use this for the [BrowsingTopics and other API's we're removing](https://github.com/duckduckgo/content-scope-scripts/blob/main/src/features/google-rejected.js) but we do lots of other things in the extension that still needs host permissions. For example we're doing [canvas fingerprint resistance](https://github.com/duckduckgo/content-scope-scripts/blob/main/src/features/fingerprinting-canvas.js) amongst others in that directory.

So the [permissions we currently use](https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/develop/browsers/chrome/manifest.json#L67-L76) also is for the code there; which includes injecting email autofill.

Another rationale not to move to that API was to prevent users being stranded without when the permissions change and the browser prompts the user to modify permissions. From experience this has a very high drop off of users when permissions in the extension are modified.

Happy to discuss further over video if that helps?

**Comment by mikewest** [comment]
Hey Jonathan!

> we do lots of other things in the extension that still needs host permissions

Understood. If you need host permissions for other modifications, then it would indeed be difficult to drop them.

> Additionally we also have the ability to disable the protections per domain to prevent breakage; something we'd probably want if we were to switch to that API.

This is possible for the set of properties controlled through [`chrome.contentSettings`](https://developer.chrome.com/docs/extensions/reference/contentSettings/). I don't recall if the privacy sandbox bits in particular are implemented that way, but it's at least conceptually possible if that was a blocker.

> Another rationale not to move to that API was to prevent users being stranded without when the permissions change and the browser prompts the user to modify permissions.

That's a reasonable concern. One way to approach it would be to specify `privacy` as an optional permission, and then request it at a reasonable time through [`chrome.permissions.request`](https://developer.chrome.com/docs/extensions/reference/permissions/). That path wouldn't cause users to be stranded, as rejection doesn't equate to uninstallation.

**Comment by jonathanKingston** [comment]
Just to note, I don't think there is an obvious path forward to preventing your concerns here due to the permissions issue.

I'm going to close this out; however please let me know if there's something else that has progressed in this time that I might have missed.

/cc @sammacbeth @kzar as extension owners.
